#pragma once

/** @file lds_n.hpp
 *  @brief N-dimensional Halton sequence generator with runtime polymorphism.
 */

#include <memory>  // for unique_ptr
#include <vector>  // for vector

#include "lds.hpp"  // for GeneratorBase, SequenceGenerator, VdCorput

namespace ldsgen {
    using std::vector;

    /**
     * @brief Halton(n) sequence generator
     *
     * The `HaltonN` class is a sequence generator that generates points in a
     * N-dimensional space using the Halton sequence. The Halton sequence is a
     * low-discrepancy sequence that is commonly used in quasi-Monte Carlo methods.
     * It is generated by iterating over two different bases and calculating the
     * fractional parts of the numbers in those bases. The `HaltonN` class keeps
     * track of the current count and bases, and provides a `pop()` method that
     * returns the next point in the sequence as a `std::vector<double>`.
     *
     * @verbatim
     *     HaltonN([2,3,5]) sequence (3D):
     *     pop() -> [0.5, 0.333, 0.2]    (VdC bases [2,3,5])
     *     pop() -> [0.25, 0.666, 0.4]   (next in each sequence)
     *     pop() -> [0.75, 0.111, 0.6]   (etc...)
     *     ...
     * @endverbatim
     */
    class HaltonN : public GeneratorBase<HaltonN, vector<double>> {
      private:
        vector<std::unique_ptr<VdCorput>> vdcs;

      public:
        /**
         * @brief Construct a new Halton N object
         *
         * Constructs an N-dimensional Halton sequence generator with the specified bases.
         *
         * @param[in] base vector of unsigned long values representing the bases for each dimension
         */
        explicit HaltonN(const vector<unsigned long>& base) {
            for (const auto& base_value : base) {
                this->vdcs.emplace_back(std::make_unique<ldsgen::VdCorput>(base_value));
            }
        }

        /**
         * @brief Evaluate the N-dimensional Halton point at a given index (pure, no state change)
         *
         * @f[
         *     H(n) = (\phi_{b_1}(n), \phi_{b_2}(n), \dots, \phi_{b_N}(n))
         * @f]
         *
         * @param[in] n The sequence index.
         * @return vector<double> the N-dimensional Halton point for index n.
         */
        auto value_at(unsigned long n) const -> vector<double> {
            auto res = vector<double>{};
            for (const auto& vdc : this->vdcs) {
                res.emplace_back(vdc->value_at(n));
            }
            return res;
        }
    };

    // Compile-time contract check: HaltonN satisfies the protocol concept.
    static_assert(SequenceGenerator<HaltonN, vector<double>>);

}  // namespace ldsgen
