#pragma once

#include <memory>   // for unique_ptr
#include <cstddef>  // for size_t

// #include <algorithm>  // for std::transform
// #include <iterator>
#include <vector>  // for vector

#include "lds.hpp"  // for VdCorput, Sphere

namespace ldsgen {
    using std::vector;

    /**
     * @brief Halton(n) sequence generator
     *
     * The `HaltonN` class is a sequence generator that generates points in a
     * N-dimensional space using the Halton sequence. The Halton sequence is a
     * low-discrepancy sequence that is commonly used in quasi-Monte Carlo methods.
     * It is generated by iterating over two different bases and calculating the
     * fractional parts of the numbers in those bases. The `HaltonN` class keeps
     * track of the current count and bases, and provides a `pop()` method that
     * returns the next point in the sequence as a `std::vector<double>`.
     *
     * ```svgbob
     *     HaltonN([2,3,5]) sequence (3D):
     *     pop() -> [0.5, 0.333, 0.2]    (VdC bases [2,3,5])
     *     pop() -> [0.25, 0.666, 0.4]   (next in each sequence)
     *     pop() -> [0.75, 0.111, 0.6]   (etc...)
     *     ...
     * ```
     */
    class HaltonN {
      private:
        vector<std::unique_ptr<VdCorput>> vdcs;

      public:
        /**
         * @brief Construct a new Halton N object
         *
         * Constructs an N-dimensional Halton sequence generator with the specified bases.
         *
         * @param[in] base vector of size_t values representing the bases for each dimension
         */
        explicit HaltonN(const vector<size_t>& base) {
            for (const auto& base_value : base) {
                this->vdcs.emplace_back(std::make_unique<ldsgen::VdCorput>(base_value));
            }
        }

        /**
         * @brief Generate the next point in the N-dimensional Halton sequence
         *
         * Returns the next point in the N-dimensional Halton sequence as a vector of double values.
         *
         * @return vector<double> the next point in the sequence
         */
        auto pop() -> vector<double> {
            auto res = vector<double>{};
            for (auto& vdc : this->vdcs) {
                res.emplace_back(vdc->pop());
            }
            return res;
        }

        /**
         * @brief Reset the state of the HaltonN sequence generator
         *
         * Resets the state of the sequence generator to a specific seed value.
         *
         * @param[in] seed the seed value to reset the sequence generator to
         */
        auto reseed(size_t seed) -> void {
            for (auto& vdc : this->vdcs) {
                vdc->reseed(seed);
            }
        }
    };

}  // namespace ldsgen
